name: Email-Send-Test
version: 2.00
abstract: Captures emails sent via Email::Send for testing
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.80
requires:
  perl: 5.005
  Email::Send: 2.00
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.45
